// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v2.0.50727.1433
//
namespace Spell {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="periodictableSoap", Namespace="http://www.webserviceX.NET")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class periodictable : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAtomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAtomicWeightOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAtomicNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetElementSymbolOperationCompleted;
        
        public periodictable() {
            this.Url = "http://www.webservicex.net/periodictable.asmx";
        }
        
        public event GetAtomsCompletedEventHandler GetAtomsCompleted;
        
        public event GetAtomicWeightCompletedEventHandler GetAtomicWeightCompleted;
        
        public event GetAtomicNumberCompletedEventHandler GetAtomicNumberCompleted;
        
        public event GetElementSymbolCompletedEventHandler GetElementSymbolCompleted;
        
        /// <remarks>
///Get element 
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetAtoms", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string GetAtoms() {
            object[] results = this.Invoke("GetAtoms", new object[0]);
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginGetAtoms(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAtoms", new object[0], callback, asyncState);
        }
        
        public string EndGetAtoms(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void GetAtomsAsync() {
            this.GetAtomsAsync(null);
        }
        
        public void GetAtomsAsync(object userState) {
            if ((this.GetAtomsOperationCompleted == null)) {
                this.GetAtomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAtomsCompleted);
            }
            this.InvokeAsync("GetAtoms", new object[0], this.GetAtomsOperationCompleted, userState);
        }
        
        private void OnGetAtomsCompleted(object arg) {
            if ((this.GetAtomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAtomsCompleted(this, new GetAtomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Get atomic wieght by element name 
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetAtomicWeight", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string GetAtomicWeight(string ElementName) {
            object[] results = this.Invoke("GetAtomicWeight", new object[] {
                        ElementName});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginGetAtomicWeight(string ElementName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAtomicWeight", new object[] {
                        ElementName}, callback, asyncState);
        }
        
        public string EndGetAtomicWeight(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void GetAtomicWeightAsync(string ElementName) {
            this.GetAtomicWeightAsync(ElementName, null);
        }
        
        public void GetAtomicWeightAsync(string ElementName, object userState) {
            if ((this.GetAtomicWeightOperationCompleted == null)) {
                this.GetAtomicWeightOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAtomicWeightCompleted);
            }
            this.InvokeAsync("GetAtomicWeight", new object[] {
                        ElementName}, this.GetAtomicWeightOperationCompleted, userState);
        }
        
        private void OnGetAtomicWeightCompleted(object arg) {
            if ((this.GetAtomicWeightCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAtomicWeightCompleted(this, new GetAtomicWeightCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Get atomic Number by element name 
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetAtomicNumber", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string GetAtomicNumber(string ElementName) {
            object[] results = this.Invoke("GetAtomicNumber", new object[] {
                        ElementName});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginGetAtomicNumber(string ElementName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAtomicNumber", new object[] {
                        ElementName}, callback, asyncState);
        }
        
        public string EndGetAtomicNumber(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void GetAtomicNumberAsync(string ElementName) {
            this.GetAtomicNumberAsync(ElementName, null);
        }
        
        public void GetAtomicNumberAsync(string ElementName, object userState) {
            if ((this.GetAtomicNumberOperationCompleted == null)) {
                this.GetAtomicNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAtomicNumberCompleted);
            }
            this.InvokeAsync("GetAtomicNumber", new object[] {
                        ElementName}, this.GetAtomicNumberOperationCompleted, userState);
        }
        
        private void OnGetAtomicNumberCompleted(object arg) {
            if ((this.GetAtomicNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAtomicNumberCompleted(this, new GetAtomicNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks>
///Get atomic symbol by element name 
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetElementSymbol", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string GetElementSymbol(string ElementName) {
            object[] results = this.Invoke("GetElementSymbol", new object[] {
                        ElementName});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginGetElementSymbol(string ElementName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetElementSymbol", new object[] {
                        ElementName}, callback, asyncState);
        }
        
        public string EndGetElementSymbol(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void GetElementSymbolAsync(string ElementName) {
            this.GetElementSymbolAsync(ElementName, null);
        }
        
        public void GetElementSymbolAsync(string ElementName, object userState) {
            if ((this.GetElementSymbolOperationCompleted == null)) {
                this.GetElementSymbolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetElementSymbolCompleted);
            }
            this.InvokeAsync("GetElementSymbol", new object[] {
                        ElementName}, this.GetElementSymbolOperationCompleted, userState);
        }
        
        private void OnGetElementSymbolCompleted(object arg) {
            if ((this.GetElementSymbolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetElementSymbolCompleted(this, new GetElementSymbolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    public partial class GetAtomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAtomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void GetAtomsCompletedEventHandler(object sender, GetAtomsCompletedEventArgs args);
    
    public partial class GetAtomicWeightCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAtomicWeightCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void GetAtomicWeightCompletedEventHandler(object sender, GetAtomicWeightCompletedEventArgs args);
    
    public partial class GetAtomicNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAtomicNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void GetAtomicNumberCompletedEventHandler(object sender, GetAtomicNumberCompletedEventArgs args);
    
    public partial class GetElementSymbolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetElementSymbolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void GetElementSymbolCompletedEventHandler(object sender, GetElementSymbolCompletedEventArgs args);
}
